AWSTemplateFormatVersion: '2010-09-09'
Description: >
  SageMaker AI Domain with S3 and MLflow for ML training pipelines.
  Supports IAM user authentication.

Parameters:
  ProjectName:
    Type: String
    Default: sm-mlflow-optuna
    Description: Name prefix for all resources

  BucketName:
    Type: String
    Description: S3 bucket name (required)

  UserProfileName:
    Type: String
    Description: Name for the SageMaker user profile (required)

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC for SageMaker Domain

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for SageMaker Domain (private subnets recommended)

  SpaceInstanceType:
    Type: String
    Default: ml.t3.medium
    AllowedValues:
      - ml.t3.medium
      - ml.t3.large
      - ml.m5.large
      - ml.m5.xlarge
      - ml.c5.large
    Description: Instance type for JupyterLab and Code Editor spaces

  MLflowServerSize:
    Type: String
    Default: Small
    AllowedValues:
      - Small
      - Medium
      - Large
    Description: Size of the MLflow tracking server

Resources:
  #############################################
  # S3 Bucket
  #############################################
  
  MainBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  #############################################
  # Security Group
  #############################################

  SageMakerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-sg'
      GroupDescription: Security group for SageMaker Domain
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  SageMakerSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SageMakerSecurityGroup
      IpProtocol: -1
      SourceSecurityGroupId: !Ref SageMakerSecurityGroup

  #############################################
  # Lifecycle Configuration
  #############################################

  JupyterLabLifecycleConfig:
    Type: AWS::SageMaker::StudioLifecycleConfig
    Properties:
      StudioLifecycleConfigName: !Sub '${ProjectName}-jupyter-setup'
      StudioLifecycleConfigAppType: JupyterLab
      StudioLifecycleConfigContent:
        Fn::Base64: |
          #!/bin/bash
          set -e
          echo "Starting lifecycle configuration..."
          cd /home/sagemaker-user
          
          # Install project dependencies
          pip install --upgrade pip
          pip install optuna mlflow xgboost
          
          echo "Lifecycle configuration complete!"
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  #############################################
  # IAM Role
  #############################################

  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-execution-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
      Policies:
        - PolicyName: MLflowAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sagemaker-mlflow:*
                Resource: '*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  #############################################
  # Space Execution Role
  #############################################

  SpaceExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-space-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
      Policies:
        - PolicyName: AdditionalPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: '*'
        - PolicyName: MLflowAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sagemaker-mlflow:*
                Resource: '*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  #############################################
  # SageMaker Domain
  #############################################

  SageMakerDomain:
    Type: AWS::SageMaker::Domain
    DependsOn: JupyterLabLifecycleConfig
    Properties:
      DomainName: !Ref ProjectName
      AuthMode: IAM
      VpcId: !Ref VpcId
      SubnetIds: !Ref SubnetIds
      AppNetworkAccessType: PublicInternetOnly
      DefaultUserSettings:
        ExecutionRole: !GetAtt SageMakerExecutionRole.Arn
        SecurityGroups:
          - !Ref SageMakerSecurityGroup
        SharingSettings:
          NotebookOutputOption: Allowed
          S3OutputPath: !Sub 's3://${MainBucket}/sharing'
        JupyterLabAppSettings:
          LifecycleConfigArns:
            - !GetAtt JupyterLabLifecycleConfig.StudioLifecycleConfigArn
          DefaultResourceSpec:
            InstanceType: !Ref SpaceInstanceType
            LifecycleConfigArn: !GetAtt JupyterLabLifecycleConfig.StudioLifecycleConfigArn
      DefaultSpaceSettings:
        ExecutionRole: !GetAtt SageMakerExecutionRole.Arn
        SecurityGroups:
          - !Ref SageMakerSecurityGroup
        JupyterLabAppSettings:
          DefaultResourceSpec:
            InstanceType: !Ref SpaceInstanceType
            LifecycleConfigArn: !GetAtt JupyterLabLifecycleConfig.StudioLifecycleConfigArn
      DomainSettings:
        DockerSettings:
          EnableDockerAccess: ENABLED
          VpcOnlyTrustedAccounts:
            - !Ref AWS::AccountId
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  #############################################
  # SageMaker User Profile
  #############################################

  SageMakerUserProfile:
    Type: AWS::SageMaker::UserProfile
    Properties:
      DomainId: !Ref SageMakerDomain
      UserProfileName: !Ref UserProfileName
      UserSettings:
        ExecutionRole: !GetAtt SageMakerExecutionRole.Arn
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  #############################################
  # SageMaker Private Space
  #############################################

  SageMakerSpace:
    Type: AWS::SageMaker::Space
    DependsOn: 
      - SageMakerUserProfile
      - JupyterLabLifecycleConfig
      - SpaceExecutionRole
    Properties:
      DomainId: !Ref SageMakerDomain
      SpaceName: !Sub '${UserProfileName}-space'
      OwnershipSettings:
        OwnerUserProfileName: !Ref UserProfileName
      SpaceSharingSettings:
        SharingType: Private
      SpaceSettings:
        AppType: JupyterLab
        SpaceStorageSettings:
          EbsStorageSettings:
            EbsVolumeSizeInGb: 20
        JupyterLabAppSettings:
          DefaultResourceSpec:
            InstanceType: !Ref SpaceInstanceType
            LifecycleConfigArn: !GetAtt JupyterLabLifecycleConfig.StudioLifecycleConfigArn
        CodeEditorAppSettings:
          DefaultResourceSpec:
            InstanceType: !Ref SpaceInstanceType
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  #############################################
  # MLflow Tracking Server
  #############################################

  MLflowTrackingServer:
    Type: AWS::SageMaker::MlflowTrackingServer
    DependsOn: SageMakerDomain
    Properties:
      TrackingServerName: !Sub '${ProjectName}-mlflow'
      ArtifactStoreUri: !Sub 's3://${MainBucket}/mlflow'
      RoleArn: !GetAtt SageMakerExecutionRole.Arn
      TrackingServerSize: !Ref MLflowServerSize
      AutomaticModelRegistration: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  DomainId:
    Description: SageMaker Domain ID
    Value: !Ref SageMakerDomain
    Export:
      Name: !Sub '${ProjectName}-DomainId'

  DomainArn:
    Description: SageMaker Domain ARN
    Value: !GetAtt SageMakerDomain.DomainArn
    Export:
      Name: !Sub '${ProjectName}-DomainArn'

  DomainUrl:
    Description: SageMaker Domain URL
    Value: !GetAtt SageMakerDomain.Url
    Export:
      Name: !Sub '${ProjectName}-DomainUrl'

  UserProfileArn:
    Description: User Profile ARN
    Value: !GetAtt SageMakerUserProfile.UserProfileArn
    Export:
      Name: !Sub '${ProjectName}-UserProfileArn'

  SpaceArn:
    Description: Private Space ARN
    Value: !GetAtt SageMakerSpace.SpaceArn
    Export:
      Name: !Sub '${ProjectName}-SpaceArn'

  BucketName:
    Description: S3 bucket for all project data
    Value: !Ref MainBucket
    Export:
      Name: !Sub '${ProjectName}-Bucket'

  SageMakerExecutionRoleArn:
    Description: SageMaker execution role ARN
    Value: !GetAtt SageMakerExecutionRole.Arn
    Export:
      Name: !Sub '${ProjectName}-ExecutionRoleArn'

  SpaceExecutionRoleArn:
    Description: Space execution role ARN
    Value: !GetAtt SpaceExecutionRole.Arn
    Export:
      Name: !Sub '${ProjectName}-SpaceRoleArn'

  DataPath:
    Description: S3 path for training data
    Value: !Sub 's3://${MainBucket}/data'

  ArtifactsPath:
    Description: S3 path for ML artifacts
    Value: !Sub 's3://${MainBucket}/artifacts'

  MLflowPath:
    Description: S3 path for MLflow artifacts
    Value: !Sub 's3://${MainBucket}/mlflow'

  MLflowTrackingServerArn:
    Description: MLflow Tracking Server ARN
    Value: !GetAtt MLflowTrackingServer.TrackingServerArn
    Export:
      Name: !Sub '${ProjectName}-MLflowArn'
