AWSTemplateFormatVersion: '2010-09-09'
Description: >
  SageMaker AI Domain with S3 and Feature Store for FM Gambling Recommendation Pipeline.
  Supports IAM user authentication.

Parameters:
  ProjectName:
    Type: String
    Default: fm-gambling-recommender
    Description: Name prefix for all resources

  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Deployment environment

  UserProfileName:
    Type: String
    Default: ryan
    Description: Name for the SageMaker user profile

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC for SageMaker Domain

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for SageMaker Domain (private subnets recommended)

  EnableFeatureStore:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: Whether to create Feature Store resources

  SpaceInstanceType:
    Type: String
    Default: ml.t3.medium
    AllowedValues:
      - ml.t3.medium
      - ml.t3.large
      - ml.m5.large
      - ml.c5.large
    Description: Instance type for JupyterLab and Code Editor spaces (under $0.60/hr)

Conditions:
  CreateFeatureStore: !Equals [!Ref EnableFeatureStore, 'true']

Resources:
  #############################################
  # S3 Bucket (Single bucket for all data)
  #############################################
  
  MainBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub '${ProjectName}-${Environment}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  #############################################
  # Security Group
  #############################################

  SageMakerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-${Environment}-sg'
      GroupDescription: Security group for SageMaker Domain
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  SageMakerSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SageMakerSecurityGroup
      IpProtocol: -1
      SourceSecurityGroupId: !Ref SageMakerSecurityGroup

  #############################################
  # Lifecycle Configuration
  #############################################

  JupyterLabLifecycleConfig:
    Type: AWS::SageMaker::StudioLifecycleConfig
    Properties:
      StudioLifecycleConfigName: !Sub '${ProjectName}-jupyter-setup'
      StudioLifecycleConfigAppType: JupyterLab
      StudioLifecycleConfigContent:
        Fn::Base64: |
          #!/bin/bash
          set -e
          echo "Starting lifecycle configuration..."
          cd /home/sagemaker-user
          
          # Install project dependencies
          pip install --upgrade pip
          pip install optuna mlflow 
          
          echo "Lifecycle configuration complete!"
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  #############################################
  # IAM Role
  #############################################

  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
      Policies:
        - PolicyName: FeatureStoreAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sagemaker:*FeatureGroup*
                  - sagemaker:GetRecord
                  - sagemaker:PutRecord
                  - sagemaker:BatchGetRecord
                  - sagemaker:DeleteRecord
                Resource: '*'
        - PolicyName: LineageAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sagemaker:*Artifact*
                  - sagemaker:*Context*
                  - sagemaker:*Action*
                  - sagemaker:*Association*
                  - sagemaker:QueryLineage
                Resource: '*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  #############################################
  # Space Execution Role (Full Permissions)
  #############################################

  SpaceExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-space-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
      Policies:
        - PolicyName: AdditionalPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: '*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  #############################################
  # SageMaker Domain
  #############################################

  SageMakerDomain:
    Type: AWS::SageMaker::Domain
    Properties:
      DomainName: !Sub '${ProjectName}-${Environment}'
      AuthMode: IAM
      VpcId: !Ref VpcId
      SubnetIds: !Ref SubnetIds
      AppNetworkAccessType: PublicInternetOnly
      DefaultUserSettings:
        ExecutionRole: !GetAtt SageMakerExecutionRole.Arn
        SecurityGroups:
          - !Ref SageMakerSecurityGroup
        SharingSettings:
          NotebookOutputOption: Allowed
          S3OutputPath: !Sub 's3://${MainBucket}/sharing'
      DefaultSpaceSettings:
        ExecutionRole: !GetAtt SageMakerExecutionRole.Arn
        SecurityGroups:
          - !Ref SageMakerSecurityGroup
      DomainSettings:
        DockerSettings:
          EnableDockerAccess: ENABLED
          VpcOnlyTrustedAccounts:
            - !Ref AWS::AccountId
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  #############################################
  # SageMaker User Profile
  #############################################

  SageMakerUserProfile:
    Type: AWS::SageMaker::UserProfile
    Properties:
      DomainId: !Ref SageMakerDomain
      UserProfileName: !Ref UserProfileName
      UserSettings:
        ExecutionRole: !GetAtt SageMakerExecutionRole.Arn
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  #############################################
  # SageMaker Private Space
  #############################################

  SageMakerSpace:
    Type: AWS::SageMaker::Space
    DependsOn: 
      - SageMakerUserProfile
      - JupyterLabLifecycleConfig
      - SpaceExecutionRole
    Properties:
      DomainId: !Ref SageMakerDomain
      SpaceName: !Sub '${UserProfileName}-space'
      OwnershipSettings:
        OwnerUserProfileName: !Ref UserProfileName
      SpaceSharingSettings:
        SharingType: Private
      SpaceSettings:
        AppType: JupyterLab
        SpaceStorageSettings:
          EbsStorageSettings:
            EbsVolumeSizeInGb: 20
        JupyterLabAppSettings:
          DefaultResourceSpec:
            InstanceType: !Ref SpaceInstanceType
            LifecycleConfigArn: !GetAtt JupyterLabLifecycleConfig.StudioLifecycleConfigArn
        CodeEditorAppSettings:
          DefaultResourceSpec:
            InstanceType: !Ref SpaceInstanceType
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  #############################################
  # Feature Store - User Features
  #############################################

  UserFeaturesGroup:
    Type: AWS::SageMaker::FeatureGroup
    Condition: CreateFeatureStore
    Properties:
      FeatureGroupName: !Sub '${ProjectName}-user-features'
      RecordIdentifierFeatureName: user_id
      EventTimeFeatureName: event_time
      OnlineStoreConfig:
        EnableOnlineStore: true
      OfflineStoreConfig:
        S3StorageConfig:
          S3Uri: !Sub 's3://${MainBucket}/feature-store/user-features'
        DisableGlueTableCreation: false
      FeatureDefinitions:
        - FeatureName: user_id
          FeatureType: String
        - FeatureName: event_time
          FeatureType: Fractional
        - FeatureName: vip_tier
          FeatureType: String
        - FeatureName: region
          FeatureType: String
        - FeatureName: age_group
          FeatureType: String
        - FeatureName: total_sessions
          FeatureType: Integral
        - FeatureName: avg_bet_amount
          FeatureType: Fractional
        - FeatureName: favorite_game_type
          FeatureType: String
      RoleArn: !GetAtt SageMakerExecutionRole.Arn
      Description: User features for FM model
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  #############################################
  # Feature Store - Game Features
  #############################################

  GameFeaturesGroup:
    Type: AWS::SageMaker::FeatureGroup
    Condition: CreateFeatureStore
    Properties:
      FeatureGroupName: !Sub '${ProjectName}-game-features'
      RecordIdentifierFeatureName: game_id
      EventTimeFeatureName: event_time
      OnlineStoreConfig:
        EnableOnlineStore: true
      OfflineStoreConfig:
        S3StorageConfig:
          S3Uri: !Sub 's3://${MainBucket}/feature-store/game-features'
        DisableGlueTableCreation: false
      FeatureDefinitions:
        - FeatureName: game_id
          FeatureType: String
        - FeatureName: event_time
          FeatureType: Fractional
        - FeatureName: game_type
          FeatureType: String
        - FeatureName: rtp
          FeatureType: Fractional
        - FeatureName: volatility
          FeatureType: String
        - FeatureName: min_bet
          FeatureType: Fractional
        - FeatureName: max_bet
          FeatureType: Fractional
      RoleArn: !GetAtt SageMakerExecutionRole.Arn
      Description: Game features for FM model
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  #############################################
  # Feature Store - Interaction Features
  #############################################

  InteractionFeaturesGroup:
    Type: AWS::SageMaker::FeatureGroup
    Condition: CreateFeatureStore
    Properties:
      FeatureGroupName: !Sub '${ProjectName}-interaction-features'
      RecordIdentifierFeatureName: interaction_id
      EventTimeFeatureName: event_time
      OnlineStoreConfig:
        EnableOnlineStore: true
      OfflineStoreConfig:
        S3StorageConfig:
          S3Uri: !Sub 's3://${MainBucket}/feature-store/interaction-features'
        DisableGlueTableCreation: false
      FeatureDefinitions:
        - FeatureName: interaction_id
          FeatureType: String
        - FeatureName: event_time
          FeatureType: Fractional
        - FeatureName: user_id
          FeatureType: String
        - FeatureName: game_id
          FeatureType: String
        - FeatureName: bet_qty
          FeatureType: Integral
        - FeatureName: total_stake
          FeatureType: Fractional
      RoleArn: !GetAtt SageMakerExecutionRole.Arn
      Description: Interaction features for FM training
      Tags:
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  DomainId:
    Description: SageMaker Domain ID
    Value: !Ref SageMakerDomain
    Export:
      Name: !Sub '${ProjectName}-DomainId'

  DomainArn:
    Description: SageMaker Domain ARN
    Value: !GetAtt SageMakerDomain.DomainArn
    Export:
      Name: !Sub '${ProjectName}-DomainArn'

  DomainUrl:
    Description: SageMaker Domain URL
    Value: !GetAtt SageMakerDomain.Url
    Export:
      Name: !Sub '${ProjectName}-DomainUrl'

  UserProfileArn:
    Description: User Profile ARN
    Value: !GetAtt SageMakerUserProfile.UserProfileArn
    Export:
      Name: !Sub '${ProjectName}-UserProfileArn'

  SpaceArn:
    Description: Private Space ARN
    Value: !GetAtt SageMakerSpace.SpaceArn
    Export:
      Name: !Sub '${ProjectName}-SpaceArn'

  BucketName:
    Description: S3 bucket for all project data
    Value: !Ref MainBucket
    Export:
      Name: !Sub '${ProjectName}-Bucket'

  SageMakerExecutionRoleArn:
    Description: SageMaker execution role ARN
    Value: !GetAtt SageMakerExecutionRole.Arn
    Export:
      Name: !Sub '${ProjectName}-SageMakerRoleArn'

  SpaceExecutionRoleArn:
    Description: Space execution role ARN (full S3/ECR permissions)
    Value: !GetAtt SpaceExecutionRole.Arn
    Export:
      Name: !Sub '${ProjectName}-SpaceRoleArn'

  UserFeaturesGroupName:
    Condition: CreateFeatureStore
    Description: User features Feature Group
    Value: !Ref UserFeaturesGroup

  GameFeaturesGroupName:
    Condition: CreateFeatureStore
    Description: Game features Feature Group
    Value: !Ref GameFeaturesGroup

  InteractionFeaturesGroupName:
    Condition: CreateFeatureStore
    Description: Interaction features Feature Group
    Value: !Ref InteractionFeaturesGroup

  # S3 Paths for reference
  DataPath:
    Description: S3 path for training data
    Value: !Sub 's3://${MainBucket}/data'

  ArtifactsPath:
    Description: S3 path for ML artifacts
    Value: !Sub 's3://${MainBucket}/artifacts'

  FeatureStorePath:
    Description: S3 path for Feature Store
    Value: !Sub 's3://${MainBucket}/feature-store'

  MLflowPath:
    Description: S3 path for MLflow artifacts
    Value: !Sub 's3://${MainBucket}/mlflow'
